baseurl = "http://www.nickhatley.com"
title = "Nick Hatley" 
theme = "hugo-coder" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.


ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

pygmentsstyle = "b2"
pygmentsnoclasses = true
pygmentslinenos = "table"
pygmentscodefencesguesssyntax = true


[params]
    author = "Nick Hatley"
    description = "A place for things"
    keywords = "MLB, NBA, rstats, NHL, politics"
    info = "A place for things"

    hideCredits = false
    hideCopyright = false

    # Custom CSS
	custom_css = []
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/nhatley"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/nhatley/"


[[menu.main]]
    name = "Baseball"
    weight = 1
    url  = "/baseball/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
[[menu.main]]
    name = "Home"
    weight = 5
    url = "/"
