baseurl = "http://www.nickhatley.com"

theme = "hugo-coder"

languagecode = "en"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[params]
    author = "Nick Hatley"
    description = "A place for things"
    keywords = "MLB, NBA, rstats, NHL, politics"
    info = "A place for things"

    hideCredits = false
    hideCopyright = false

    # Custom CSS
	custom_css = []

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/nhatley"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/nhatley/"


[[menu.main]]
    name = "Baseball"
    description = "Place for baseball related post"
    url  = "/baseball/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
