---
title: "Animated Division Standings"
author: "Nick Hatley"
date: "2019-09-15"
output:
  blogdown::html_page
categories: ["R"]
slug: division_gifs

tags: ["R Markdown", "blogdown"]
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning =  FALSE)
knitr::opts_chunk$set(message = FALSE)
options(knitr.table.format = "html")
```

```{r}
library(tidyverse)
library(gganimate)
mlb_db_dir <- "~/Dropbox/mlb/"
standings <- read_rds(paste0(mlb_db_dir, "data/standings/historical/standings.rds"))
tm_colors = read_csv(paste0(mlb_db_dir, "reports/logos/mlb_colors.csv"))

source(paste0(mlb_db_dir, "code/functions/standings_gif.R"))
source(paste0(mlb_db_dir, "code/functions/plot_theme.R"))
divisions = standings %>% 
  distinct(division, league) %>% 
  mutate(div_order = case_when(
    division == "NL East" ~ 1.1,
    division == "NL Central" ~ 1.2,
    division == "NL West" ~ 1.3,
    division == "NL Overall" ~ 1.5,
    division == "AL West" ~ 2.1,
    division == "AL East" ~ 2.2,
    division == "AL Central" ~ 2.3,
    division == "AL Overall" ~ 2.5
  )) %>% 
  add_row(division = "NL Wild Card", league = "NL", div_order = 1.4) %>% 
  add_row(division = "AL Wild Card", league = "AL", div_order = 2.4)
   

```


## National League

### NL East
```{r, fig.width=10, fig.height=5, fig.show = 'animate', ffmpeg.format='gif', dev='jpeg'}
standings_gif(division_in = "NL East",
              renderer = "ffmpeg",  
              title = "division")
```

**********

### NL Central
```{r, fig.width=10, fig.height=5, fig.show = 'animate', ffmpeg.format='gif', dev='jpeg'}
standings_gif(division_in = "NL Central", 
              renderer = "ffmpeg", 
              title = "division")
```

**********

### NL West
```{r, fig.width=10, fig.height=5, fig.show = 'animate', ffmpeg.format='gif', dev='jpeg'}
standings_gif(division_in = "NL West", 
              renderer = "ffmpeg", 
              title = "division")
```

**********

### NL Wild Card
```{r, fig.width=10, fig.height=5, fig.show = 'animate', ffmpeg.format='gif', dev='jpeg'}
standings_gif(division_in = "NL Wild Card", 
              renderer = "ffmpeg", 
              title = "division")
```

**********

### NL Overall
```{r, fig.width=10, fig.height=5, fig.show = 'animate', ffmpeg.format='gif', dev='jpeg'}
standings_gif(division_in = "NL Overall", 
              renderer = "ffmpeg", 
              title = "division")
```

**********

## American League

### AL East
```{r, fig.width=10, fig.height=5, fig.show = 'animate', ffmpeg.format='gif', dev='jpeg'}
standings_gif(division_in = "AL East",
              renderer = "ffmpeg", 
              title = "division")
```

**********

### AL Central
```{r, fig.width=10, fig.height=5, fig.show = 'animate', ffmpeg.format='gif', dev='jpeg'}
standings_gif(division_in = "AL Central", 
              renderer = "ffmpeg", 
              title = "division")
```

**********

### AL West
```{r, fig.width=10, fig.height=5, fig.show = 'animate', ffmpeg.format='gif', dev='jpeg'}
standings_gif(division_in = "AL West",
              renderer = "ffmpeg", 
              title = "division")
```

**********

### AL Wild Card
```{r, fig.width=10, fig.height=5, fig.show = 'animate', ffmpeg.format='gif', dev='jpeg'}
standings_gif(division_in = "AL Wild Card", 
              renderer = "ffmpeg", 
              title = "division")
```

**********

### AL Overall
```{r, fig.width=10, fig.height=5, fig.show = 'animate', ffmpeg.format='gif', dev='jpeg'}
standings_gif(division_in = "AL Overall", 
              renderer = "ffmpeg", 
              title = "division")
```

**********