---
title: "Exit Velo Boxplots"
author: "Nick Hatley"
date: "2021-03-23"
output:
  blogdown::html_page
categories: ["R"]
slug: exit_velo_boxplots
tags: [ "hitting", "statcast", "exit velocity"]
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning =  FALSE)
knitr::opts_chunk$set(message = FALSE)
options(knitr.table.format = "html")
```


```{r get librarys, function and data}
library(tidyverse)
make_season_ev_boxplot_by_player <- function(.data){
  .data %>% 
    ggplot(aes(x = season,
               y = launch_speed,
               group = season)) + 
    geom_boxplot(color = '#13274F', fill = "#f8f2e4", alpha = .5) +  
    ggforce::facet_row(vars(player_name_lbl)) + 
    plot_theme_facet_grid() +
    scale_y_continuous(limits = c(25, 125),
                       breaks = c(seq(25, 75, by = 25), seq(85, 115, by = 5)),
                       labels = c(seq(25, 75, by = 25), seq(85, 115, by = 5))) + 
    scale_x_continuous(breaks = seq(2015, 2020, by = 1),
                       labels = c('2015', "'16", "'17", "'18", "'19", "2020")) + 
    ggtitle("Exit Velocity Seasons 2015 - 2020") + 
    theme(panel.grid.minor = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.major.y = element_line(color = "#A4A4A4", 
                                            size = .4, linetype = 'dotted'),
          axis.title = element_blank(), 
          strip.text = element_text(face = 'bold'))
  
}


mlb_db_dir = "~/Dropbox/mlb/"
p_tables <- read_rds(paste0(mlb_db_dir, 'output/plots/exit_velocity/p_tables_2020.rds'))
bats_ids <- read_rds(paste0(mlb_db_dir, 'output/plots/exit_velocity/bats_ids.rds'))


divs = bats_ids %>% arrange(div_order) %>% distinct(division) %>% pull(division)
source(paste0(mlb_db_dir, "code/functions/plot_theme.R"))
```

```{r, fig.align='center', out.width = "85%", out.height= "15%"}
example_bx <- p_tables %>% 
  filter(mlbam_id_batter == 645277) %>% 
  group_by(mlbam_id_batter, season) %>% 
  mutate(mean_launch_speed = mean(launch_speed, na.rm = T),
         median_launch_speed = median(launch_speed, na.rm = T),
         max_launch_speed = max(launch_speed, na.rm = T)
  ) %>% 
  ungroup %>% 
  select(player_name, launch_speed, median_launch_speed, max_launch_speed) %>% 
  mutate(team = "How to Read This Graph", team_order = 6)

example_bx %>% 
  ggplot(aes(x = reorder(player_name, -max_launch_speed),
             y = launch_speed,
             group = player_name)) + 
  geom_boxplot(color = '#13274F', fill = "#f8f2e4", alpha = .5) +
  geom_text(aes(x = player_name,
                y = median_launch_speed,
                label = "Median"), 
            nudge_x = .46, color = "#13274F") + 
  geom_text(aes(x = player_name,
                y = 76.5,
                label = "25th\npercentile"), 
            nudge_x = -.46, color = "#13274F") + 
  geom_text(aes(x = player_name,
                y = 95,
                label = "75th\npercentile"), 
            nudge_x = -.46, color = "#13274F") + 
  geom_text(aes(x = player_name,
                y = max_launch_speed,
                label = "Max"), 
            nudge_y = .125, nudge_x = .05, color = "#13274F") +
  ggrepel::geom_label_repel(data = . %>% 
                              filter(launch_speed == min(launch_speed)) %>% 
                              mutate(launch_speed = launch_speed + .8),
                            aes(label = "Dots = outliers"),
                            nudge_x = .135, 
                            fill = "#f8f2e4", color = "#13274F",
                            segment.size = 0.2,
                            arrow = arrow(length = unit(0.025, "npc"))) +
  geom_label(data = . %>% 
               filter(launch_speed == min(launch_speed)),
             aes(label = "**Note that other graphs\nare limited to EV > 50"),
             nudge_x = -.45, 
             fill = "#f8f2e4", color = "#13274F") +
  plot_theme() +
  ggtitle("Exit Velocity (MPH) of All Batted Balls in Season") + 
  scale_y_continuous(limits = c(30, 125),
                     breaks = c(seq(50, 75, by = 25), seq(85, 115, by = 5)),
                     labels = c(seq(50, 75, by = 25), seq(85, 115, by = 5))) + 
  coord_flip() + 
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(color = "#A4A4A4", size = .4, linetype = 'dotted'),
        axis.title.y = element_blank())

```
  
***********
  
```{r, results = 'asis', fig.align='center', fig.height=10, fig.width=10}
divs = bats_ids %>% arrange(div_order) %>% distinct(division) %>% pull(division)

walk(divs, function(div_in){
  
cat(div_in, "\n")

div_teams = bats_ids %>% 
    filter(division == div_in) %>%
    distinct(team) %>%
    pull(team)  

bats_ids_div = bats_ids %>% 
  filter(team %in% div_teams)  

p_tables_div = p_tables %>% 
  filter(mlbam_id_batter %in% bats_ids_div$mlbam_id) %>% 
  left_join(bats_ids_div %>% select(mlbam_id_batter = mlbam_id, team) %>% 
              distinct %>% 
              mutate(team_order = dense_rank(team))
  )

p_tables_names_and_ids <- p_tables_div %>% 
  distinct(mlbam_id_batter, player_name) %>% 
  group_by(mlbam_id_batter) %>% 
  slice(1) %>% 
  ungroup %>% 
  mutate(player_name_lbl = str_replace(player_name, "\\s", "\n")) 

p_tables_div <- p_tables_div %>% 
  select(-player_name) %>% 
  left_join(p_tables_names_and_ids) %>% 
  drop_na %>% 
  group_by(mlbam_id_batter, season) %>% 
  mutate(mean_launch_speed = mean(launch_speed, na.rm = T),
         median_launch_speed = median(launch_speed, na.rm = T),
         max_launch_speed = max(launch_speed, na.rm = T)
  ) %>% 
  ungroup 

p_tables_ev_lbl = p_tables_div %>%
  filter(season == 2020) %>% 
  distinct(mlbam_id_batter, player_name_lbl, mean_launch_speed, 
           median_launch_speed, max_launch_speed)  %>%
  mutate(launch_speed = 100)

p_order = p_tables_ev_lbl %>%  
  arrange(desc(max_launch_speed)) %>% 
  mutate(p_order_2020_max = 1:n()) %>%  
  arrange(desc(mean_launch_speed)) %>% 
  mutate(p_order_2020_mean = 1:n()) %>% 
  arrange(desc(median_launch_speed)) %>% 
  mutate(p_order_2020_median = 1:n()) %>% 
  select(-ends_with("_speed"))

p_df <- p_tables_div %>% 
  left_join(p_order) %>% 
  mutate(player_name_lbl = fct_reorder(player_name_lbl, p_order_2020_max))

p <- p_df %>% 
  mutate(team = str_to_title(team)) %>%
  mutate(team = fct_reorder(team, team_order)) %>% 
  ggplot(aes(x = reorder(player_name, max_launch_speed),
             y = launch_speed,
             group = player_name)) + 
  geom_boxplot(color = '#13274F', fill = "#f8f2e4", alpha = .5) + 
  ggforce::facet_col(vars(team), scales = 'free', space = 'free') + 
  plot_theme_facet_grid() +
  scale_y_continuous(limits = c(50, 125),
                     breaks = c(seq(50, 75, by = 25), seq(85, 115, by = 5)),
                     labels = c(seq(50, 75, by = 25), seq(85, 115, by = 5))) + 
  coord_flip() + 
  ggtitle("Exit Velocity (MPH) on all batted balls in 2020") + 
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_line(color = "#A4A4A4", size = .4, linetype = 'dotted'),
        panel.grid.major.y = element_blank(),
        axis.title = element_blank())

plot(p)  
cat("\n")
cat("<br>")
})


```
  
***********
  
