---
title: "WRCplus Distributions"
author: "Nick Hatley"
date: "2019-08-28"
output:
  blogdown::html_page
categories: ["R"]
slug: wrc_plus

tags: ["R Markdown", "blogdown"]
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning =  FALSE)
knitr::opts_chunk$set(message = FALSE)
options(knitr.table.format = "html")
```


```{r get librarys, function and data}
library(tidyverse)
wrc <- read_rds("../../../mlb_db/output/wrc_plus.rds")

color_manual = c(
  "league" = "gray54",
  "team" = "#CE1141"
)


##plot 
wrc_team = wrc %>% distinct(team_flag, team, mean_wrc_plus) %>% filter(team != "league") %>% 
  mutate(label = ifelse(team == "astros", 
                        paste0("Mean wrc+\n", round(mean_wrc_plus, 0)),
                        paste0(round(mean_wrc_plus, 0)))) %>% 
  mutate(team2 = ifelse(team == "league", "league", "team"))

```

```{r}
plot_theme = function (base_size = 9) {
  theme_bw(base_size = base_size) %+replace% 
    theme(plot.title = element_text( 
      size = 13, 
      margin = margin(b=4, unit = "pt"), 
      hjust = 0, vjust = 0
    ),
    plot.subtitle = element_text(
      size = 9, 
      face = "italic", 
      colour = "#595959", 
      margin = margin(b = 6, unit = "pt"), 
      hjust = 0, vjust = 0
    ), 
    plot.caption = element_text(
      size = 10,
      color = "#7F7F7F", 
      hjust = .92, vjust = 0,
      face = "italic"
    ),
    axis.title = element_text(color = "gray8", size = 10),
    axis.text = element_text(color = "gray8", size = 9), 
    
    axis.line = element_line(color = "#A4A4A4", size = .2),
    strip.text.x = element_text(color = "gray8", size = 10, margin = margin(.175,0,
                                                                         .175,0, "cm")),
    strip.text.y = element_text(color = "gray8", size = 10, margin = margin(0,.175,
                                                                            0,.175, "cm")),
    strip.background = element_rect(fill = "#f8f2e4", size = 1.2),
    
    #axis.ticks = element_line(color = "#A4A4A4", size = .2),
    axis.ticks = element_blank(),
    axis.ticks.length = unit(8, "pt"),
    legend.title = element_blank(),
    legend.margin=margin(0,0,0,0),
    legend.position = "bottom",
    legend.box.margin=margin(-5,-10, 0,-10),
    panel.grid = element_line(color = "#A4A4A4", size = .2),
    
    panel.grid.major.y = element_line(linetype = "solid", color = "#A4A4A4", size = .75),
    panel.grid.major.x = element_line(linetype = "solid", color = "#A4A4A4", size = .15),
    panel.grid.minor.y = element_line(linetype = "dotted", color = "#A4A4A4", size = .4),
    panel.grid.minor.x = element_line(linetype = "dotted", color = "#A4A4A4", size = .4),
    #panel.border = element_blank(), 
    complete = TRUE
    )
}
```

```{r, fig.height=12.5, fig.width=8.5}
wrc %>% 
  mutate(team2 = ifelse(team == "league", "league", "team")) %>% 
  mutate(team_flag = str_extract(team_flag, "^.*\\ +") %>% str_remove("\\+") %>% str_trim) %>% 
  group_by(team_flag) %>%
  fill(mean_wrc_plus) %>%
  ungroup %>%
  mutate(team_flag = paste0(team_flag, "\n", "Team wrc+ = ", round(mean_wrc_plus, 0))) %>% 
  mutate(team_flag = fct_reorder(team_flag, -mean_wrc_plus)) %>% 
  ggplot(
    aes(
      x = wrc_plus,
      fill = team2
    )
  ) +
  geom_density(#data = . %>% filter(team != "full"),
    alpha = 0.25
  ) +
  scale_fill_manual(
    values = color_manual
  ) + 
  plot_theme() +
  facet_wrap(
    vars(team_flag)
    ) + 
  scale_x_continuous(limits = c(0, 200),
                     breaks = seq(0, 200, by = 50),
                     labels = seq(0, 200, by = 50)
                     ) + 
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.title.y = element_blank(), 
        axis.text.y = element_blank()
        ) +
  ggtitle("Weighted Runs Created Plus (wrc+) distributions by team",
          subtitle = "Grey density plots represent league as a whole"
          ) +
  labs(caption = "Players with > 100 PA's. League avg for these players is 97",
       x = "wrc+")
```